// flow-typed signature: 5f381d3ec708ad60d65c581abed22f07
// flow-typed version: <<STUB>>/deepfreeze_v^2.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deepfreeze'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'deepfreeze' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deepfreeze/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deepfreeze/index' {
  declare module.exports: $Exports<'deepfreeze'>;
}
declare module 'deepfreeze/index.js' {
  declare module.exports: $Exports<'deepfreeze'>;
}
declare module 'deepfreeze/test.js' {
  declare module.exports: $Exports<'deepfreeze/test'>;
}
